### PR TITLE
Add spec file for RHEL+ rpm building

### PR DESCRIPTION
**Pull request by jornane**
Heavily inspired from #40, this .spec file will build and install on CentOS 7, Fedora 29-31 and RHEL 8 beta.

### CODE REVIEW

**Comment by jornane** [comment]
Updated to 1.8.1

**Comment by jornane** [comment]
It may be better to merge #59 instead, and make these changes in their own repo.

**Comment by robert-scheck** [comment]
I would like to encourage you to contribute to the regular radsecproxy RPM package in Fedora and EPEL rather spinning up own COPR repositories.

**Comment by jornane** [comment]
@robert-scheck I see you already had a spec file in the works, and that it's already in Fedora. This PR is no longer needed then.

**Pull request closed without merging**
