### PR TITLE
Fix sigsegv in clientwr()

### PR DESCRIPTION
**Pull request by jpereira**
Just process non-empty requests

### CODE REVIEW

**Comment by jpereira** [comment]
I've experienced the below SIGSEGV with empty requests.

```
* thread #3, name = 'radsecproxy', stop reason = signal SIGSEGV: invalid address (fault address: 0x40)
    frame #0: 0x000000000040ab81 radsecproxy`clientwr(arg=0x00000000004335b0) at radsecproxy.c:1685:42
   1682
   1683         if (rqout->tries > 0 && now.tv_sec - server->lastrcv.tv_sec > conf->retryinterval)
   1684             statusserver_requested = 1;
-> 1685         if (rqout->tries == (*rqout->rq->buf == RAD_Status_Server ? 1 : conf->retrycount + 1)) {
   1686             debug(DBG_DBG, "clientwr: removing expired packet from queue");
   1687             replylog(rqout->rq->msg, server, rqout->rq);
   1688             if (conf->statusserver == RSP_STATSRV_ON || conf->statusserver == RSP_STATSRV_MINIMAL) {
lldb> p rqout->rq
(request *) $0 = 0x0000000000000000
lldb> 
```

**Comment by fmauchle** [comment]
It would be very strange if this patch truly fixes the problem.
In essence, the exact same check is already done a few lines before (on line 1663). 
On the other hand, any code manipulating rqout->rq has a lock on it. So I would assume something else stomping on this memory.

Do you see these sigsegv with a rather minimalistic config or something more complex?

**Comment by jpereira** [comment]
If you take a look at line 1665 https://github.com/radsecproxy/radsecproxy/blob/988f446a7dfa6da0b5ab9704913819a51d9d2a8d/radsecproxy.c#L1662, you see that `if (rqout->rq)` could be FALSE. therefore, it will cause the reported SIGSEGV.

In my tests, I am using a dummy config setting proxying the auth packets to a local radiusd server. even I've sent ~150kps without crashes using such suggested fix.

**Comment by fmauchle** [comment]
I'm sorry, I still don't get it.
https://github.com/radsecproxy/radsecproxy/blob/988f446a7dfa6da0b5ab9704913819a51d9d2a8d/radsecproxy.c#L1660-L1668
If the term on line 1662 evaluates to FALSE, we don't break out of the for loop and never access `rqout->rq`. If it was the last element, we would later break out of the surrounding loop anyway:
https://github.com/radsecproxy/radsecproxy/blob/988f446a7dfa6da0b5ab9704913819a51d9d2a8d/radsecproxy.c#L1672-L1673
If you could share the minimal setup to get the crash (without the proposed fix) I will try to reproduce it.

**Pull request closed without merging**
